import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/min.scss"
import Providers from "../../context/provider"
import { getServerSession } from "next-auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode;
}



export default async function RootLayout({ children }:RootLayoutProps) {
  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}> 
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
